### ISSUE TITLE
Python binding for `StringPattern.contents` is broken

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/llvm-backend#824] opened 2023-08-11 09:43 UTC
Consider the following small script:

```python3
from pyk.kllvm import load
from pyk.kllvm.parser import parse_text

ast = parse_text(r'"\x80"')
print(ast.contents)
```

This raises the following exception:

```
Traceback (most recent call last):
  File "/home/ttoth/git/pyk/test.py", line 5, in <module>
    print(ast.contents)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

A quick solution would be to expose `contents` as `bytes` (under perhaps a different name like `raw` or `raw_contents`).
Ideally though, the bindings should take care of the conversion to a `str`, otherwise, this has to be done on the Python side, which is obviously much slower.

Without this change, a workaround in `pyk` is to parse the result of `__str__()`.

**Comment by Scott-Guest** [comment] 2023-08-15 15:31
The changes I'm making for Unicode support in the LLVM backend (#3344) will fix this without having to change the bindings.

Specifically,`\xHH` will always be stored as as (the UTF-8 encoding of) `U+00HH` rather than the raw byte `0xHH`.

**Comment by Scott-Guest** [comment] 2023-08-15 15:38
Closing this as a duplicate of runtimeverification/k#3344

**Closed by Scott-Guest** 2023-08-15 15:38 UTC
Labels: bug, bindings
