### ISSUE TITLE
Potential memory leak when using Python bindings

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/llvm-backend#770] opened 2023-05-19 15:36 UTC
When running concrete interpretation thousands of times from a single process using the Python bindings, the system eventually runs out of memory.

## Reproduction

https://github.com/runtimeverification/evm-semantics/pull/1816

1. Clone `evm-semantics`
3. Check out `llvm-interpret` 
4. Update submodules
5. Build: `make poetry deps build`
6. Run tests: `make -C ./kevm-pyk test-integration`
7. Observe memory consumption

**Comment by ehildenb** [comment] 2023-05-25 15:12
Could try different test-suites independently. The VMTests are run with `make test-vm`, so maybe pytest could separate that ouut, and the bchain tests are called with `make test-bchain`. These test-suites are in different directories, so that can probably be used to filter which tests.

If we can isolate those two test-suites, that would be a hint that probably the memory leak is happening in `CALL*` opcodes. Those opcodes do a lot of bytes manipulation (the bchain tests which have `CALL*` opcodes), which may be a hint.

**Comment by Baltoli** [comment] 2023-05-26 15:41
My thought here is that this is a manifestation of the issue described in this blog post: https://ayende.com/blog/195681-B/production-postmortem-the-memory-leak-that-only-happened-on-linux, where `posix_memalign` doesn't play ball with another allocator (here, the Python heap allocation subsystem), producing fragmentation and leaks.

The blog post describes a mechanism via `mmap()` to solve the issue; I have yet to investigate whether this will work in our use case, and I'm wary of changing details of the backend's memory subsystem without substantial testing.

As a possible workaround, I have exposed an explicit call to the backend GC to the Python bindings (https://github.com/runtimeverification/llvm-backend/pull/776). If we call this after each test, it may reduce the pressure to allocate new megabyte blocks in the backend and therefore decrease fragmentation and leaks.

**Comment by Baltoli** [comment] 2023-06-05 16:08
Summary of discussion 5/6:

* @dwightguth agrees that the issue is likely to be with `posix_memalign` re. fragmentation and overallocation.
* The garbage collector's core algorithmic requirement is that the core block allocator hands over blocks of 1MB aligned memory; this allows it to do fast block detection by rounding down addresses.
* The solution here is likely to be to roll our own version of the functionality provided by `posix_memalign` using `mmap`; we can map a 16MB region and align it to a megabyte boundary by hand.

**Comment by Baltoli** [comment] 2023-12-06 13:29
The issue isn't quite as described above, per my recollection from subsequently looking into it. My understanding is that the semantics evaluates a function that requires a big total memory allocation[^gc], then this memory is never returned to the OS, even if the backend's GC runs.

The solution is probably one, both or a combination of:
* Allow memory to be returned to the OS via `free`; this will require us to do some compaction on collection I think
* Finish implementing @theo25's work on making the GC runnable within functions

[^gc]: Garbage collection won't run _within_ a function call, only between rewrite steps.

**Comment by Baltoli** [comment] 2023-12-20 21:38
I presume that this is closed by #945 and https://github.com/runtimeverification/pyk/pull/798; I reproduced what appears to be a similar leaky program but we didn't run the full EVM version of the reproduction again as it's too old to do easily. @tothtamas28 if this recurs when we attempt to move the EVM conformance tests over to the bindings again we can reopen.

**Closed by Baltoli** 2023-12-20 21:38 UTC
Labels: bindings
